import type { AvatarAppearance } from "@3dspace/contracts";

// Hint colors shown in the picker before a zone is explicitly set.
// Not saved — null zones use the original baked JPG texture.
export const AVATAR_HINT_COLORS: Record<keyof AvatarAppearance, string> = {
  hairTop:     "#2a1a0e",
  hairFront:   "#2a1a0e",
  headSide:    "#2a1a0e",
  hairBack:    "#2a1a0e",
  faceSkin:    "#f0c090",
  faceAccent:  "#f0c090",
  collar:      "#ffffff",
  shirtFront:  "#4466aa",
  shirtBelly:  "#4466aa",
  shirtBack:   "#4466aa",
  shirtSide:   "#4466aa",
  shoulderTop: "#4466aa",
  shoulderCap: "#4466aa",
  sleeve:      "#4466aa",
  hand:        "#f0c090",
  thigh:       "#2a3a5a",
  shin:        "#2a3a5a",
  legSide:     "#2a3a5a",
  legBack:     "#2a3a5a",
  shoeTop:     "#1a1a1a",
  shoeToe:     "#1a1a1a",
  shoeSide:    "#1a1a1a",
  shoeSole:    "#111111",
};

// All-null = "no custom colors, use original JPG everywhere".
export const DEFAULT_APPEARANCE: AvatarAppearance = {
  hairTop:     null,
  hairFront:   null,
  headSide:    null,
  hairBack:    null,
  faceSkin:    null,
  faceAccent:  null,
  collar:      null,
  shirtFront:  null,
  shirtBelly:  null,
  shirtBack:   null,
  shirtSide:   null,
  shoulderTop: null,
  shoulderCap: null,
  sleeve:      null,
  hand:        null,
  thigh:       null,
  shin:        null,
  legSide:     null,
  legBack:     null,
  shoeTop:     null,
  shoeToe:     null,
  shoeSide:    null,
  shoeSole:    null,
};
