"use client";

import { useGLTF } from "@react-three/drei";
import { GlbHostAvatar } from "./GlbHostAvatar";
import type { WorldHostAvatarProps } from "./GlbHostAvatar";

/** Served from apps/web/public/world-hosts/; generated by scripts/prepare-robot-simple-glb.mjs. */
const URL = "/world-hosts/robot-simple.glb";
// The GLB stands 0 → 4.0 m tall. nativeHeight = 5.0 → renders at 80% of TARGET_HEIGHT (20% smaller).
const NATIVE_HEIGHT = 5.0;

/** GLB-backed World Host avatar — the simple floating-head robot. */
export function RobotSimpleHostAvatar(props: WorldHostAvatarProps) {
  return (
    <GlbHostAvatar
      {...props}
      url={URL}
      nativeHeight={NATIVE_HEIGHT}
      idleAnimation="LookAround"
    />
  );
}

useGLTF.preload(URL);
